### PR TITLE
Refactor deployment and various improvements

### PR DESCRIPTION
**Pull request by manthey**
This branch has a large number of changes.  Here is a check list for them as they get completed.
- [x] Pull all dependencies from npm or other sources instead of having them in the repo.
- [x] Use eslint and semistandard to reformat js.  This is currently our corporate formatting choice.
- [x] Use column weights and other changes for LineUp.
- [x] Prevent duplicate pairings (fixes issue #10).
- [x] Latest version of Clique (until this is done, the old version of clique remains bundled in the repo)
- [x] Newer version of Lineup (hide rename and collapse controls)
- [x] Clique graph options (default to show labels, button to toggle labels, fix multiple-load issue)
- [x] Allow separate datasets on the left and right as had been done in the past
- [x] Auto-select datasets when there is only one available
- [x] Entity table improvements (date, scroll)
- [x] Fetch profile pictures
- [x] Cache profile pictures for off-line use
- [x] Fix name autocomplete (fixes issue #13)

With the new packaging, after pulling down the branch, type `npm install`.  Because it is currently pulling in the latest version of Clique and Candela, and because those are webpacked items, the build step is very slow.  There will be a `built` directory.  Within this directory, there are some links to the source directories for convenience in development -- we should change this to copy the source instead of linking so that the built directory is the only thing needed for off-line deployments.

With the built directory, run the add via a command like `tangelo --hostname=0.0.0.0 --port=8081 -c tangelo-config.yaml -r built`.

### CODE REVIEW

**Comment by jeffbaumes** [comment]
Looking good. Hard to argue against 30K less lines of code.

**Comment by manthey** [comment]
@curtislisle Do you have to give this a try in its current state?  I know you said I could merge when I felt it was ready, but I'd rather have a second person try it out first. 

Note the change to defaults.json to allow different data sets (see the commit that reads "Better data set specification").

**Comment by curtislisle** [comment]
this sounds awesome.  I will try it over the weekend.  Sorry to be slow.  Overwhelmed a bit by two other project deliverables next week :-)

**Comment by manthey** [comment]
I'll be moving the remaining items that were collecting in this PR into separate issues, and marking this as no longer a WIP.

**Comment by manthey** [comment]
I've added the ability to resize Clique graphs (which resolves issue #32).

**Pull request merged**
